apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-servisbot-reverse-proxy
spec:
  parallelism: 1    
  completions: 1    
  template:         
    metadata:
      name: kaniko-servisbot-reverse-proxy
    spec:
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:latest
        args: [
          "--dockerfile=/godata/pipelines/servisbot-reverse-proxy/Dockerfile",
          "--context=/godata/pipelines/servisbot-reverse-proxy",
          "--destination=tfld-docker-prd-local.repo.14west.io/servisbot-reverse-proxy:latest"
        ]
        volumeMounts:
        - mountPath: /godata
          name: gocdagent-data
        - mountPath: /kaniko/.docker/config.json
          name: docker-creds
          subPath: config.json
        env:
        - name: DESITINATION
        value: tfld-docker-prd-local.repo.14west.io/servisbot-reverse-proxy:latest
      restartPolicy: Never   
      volumes:
      - name: gocdagent-data
        persistentVolumeClaim:
          claimName: gocdagent-node-and-go
      - name: docker-creds
        configMap:
          defaultMode: 420
          name: configcontent
      backoffLimit: 1
